<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90" />
    <ProjectReference Include="../../../shared/dotnet/ArchiveMediaDrive.Core/ArchiveMediaDrive.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="config.html" />
  </ItemGroup>
</Project>
